workers_dev = true
name = "tellapp"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[[d1_databases]]
binding = "TELLAPP_DB"
database_name = "tellapp-db"
database_id = "bf97a768-9f69-4eea-9204-8fb4232481b0"
preview_database_id = "a4b0b0d1-9fc2-4347-a7da-9108ab0aff07" # Required for Pages local development

[observability.logs]
enabled = true
