workers_dev = true
name = "app"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
MY_VAR = "my-variable"

[observability.logs]
enabled = true
